cropper/urls.py
from django.conf.urls import url, include
from .views import CropView

urlpatterns = [
    url(r'^(?P<app>[-\w\d]+)/(?P<model>[-\w\d]+)/(?P<obj_id>[1-9]\d*)/(?P<field>[-\w\d]+)/$', CropView.as_view(), name="crop"),
]

cropper/forms.py
from django import forms
from django.contrib.contenttypes.models import ContentType
from .models import Crop

# ROTATE_OPTIONS = (
#     (0, ''),
#     (90, '90 degrees clockwise'),
#     (270, '90 degrees counter-clockwise'),
#     (180, '180 degrees'),
# )


class CropImageForm(forms.Form):
    """ A form for cropping images on the account. """

    def __init__(self, *args, **kwargs):
        self.model = kwargs.pop('model', None)
        self.field = kwargs.pop('field')
        self.coordinates = kwargs.pop('coordinates')
        self.image = getattr(self.model, self.field)

        super(CropImageForm,self).__init__(*args,**kwargs)
        self.fields['crop'].initial = self.coordinates or ""
        self.fields['crop'].widget = forms.HiddenInput()

    crop = forms.CharField()    
    required_css_class = 'required'

    def _parse_crop_coords(self, coords):
        """ Translate coordinates (hiddenfield or charfield) into an integer list. """
        if not coords:
            return None

        parts = coords.split(',')

        if len(parts) is not 4:
            raise ValueError('Invalid number of coordinates: {0}. Should be 4'.format(len(parts)))

        # Explode of these aren't integers
        parts = [int(part) for part in parts]

        # Make tuple of tuple and return
        return parts


    def clean(self):
        cleaned_data = super(CropImageForm, self).clean()

        # Clean crop field or fail
        try:
            cleaned_data['crop'] = self._parse_crop_coords(self.cleaned_data.get('crop'))
        except Exception:
            self._errors['crop'] = self.error_class(
                ["Um... somehow you messed with the crop data. I have no sympathy. Get out."])
            if 'crop' in cleaned_data:
                cleaned_data.pop('crop')

        # Asign it to the class if it's still here
        self.coordinates = self.data.get('crop')
        return cleaned_data


    def save(self):
        """ This is what saves the cropped version. """
        if self.coordinates:
            crop = Crop.objects.get_or_create(object_id=self.model.id, 
                content_type=ContentType.objects.get_for_model(self.model), field=self.field)[0]
            crop.coordinates = self.coordinates
            crop.save()
            crop.generate()
            return crop
        return False

cropper/templates/cropper/crop.html
{% extends base_template %}
{% load thumbnail compress %}

{% block extrahead %}
    <style type="text/css">
        @import url('{{ STATIC_URL }}jcrop/css/jquery.Jcrop.css');
    </style>
{% endblock extrahead %}

{% block title %}Crop an Image{% endblock title %}

{% block content %}
    <form class="form" enctype="multipart/form-data" action="." method="post">
        {% csrf_token %}
        <div class="section">
            <img id="crop-img" class="cover" src="{{ image }}">
            {{ form.as_p }}
        </div>
        <div class="section controls">
            <input type="hidden" name="post-save-redirect" value="{{ post_save_redirect }}">
            <input class="button" name="save" type="submit" value="Save Crop" default>
            
            {% if coordinates %}            
                <input class="button" type="submit" name="delete" value="Remove Copy">
            {% endif %}

        </div>
    </form>
    
    <script src="{{ STATIC_URL }}jquery/jquery.min.js"></script>
    <script src="{{ STATIC_URL }}jcrop/js/jquery.Jcrop.js" type="text/javascript"></script>
    <script type="text/javascript">
        var DjangoCropper = function(){

            var image = $('#crop-img');
            var img_dimensions = [{{ form.image.width }}, {{ form.image.height }}];
            
            var _unconvert_crop = function(string_coords){
                // Convert PIL coordinates into jcrop coordinates
                // PIL wants the x,y of the top left corner, width and height.
                // jCrop wants the x,y of the top left corner and the bottom right corner.
                var crop = string_coords.split(',')
                for (var i = crop.length - 1; i >= 0; i--) {
                    crop[i] = parseFloat(crop[i]);
                };

                proportion = image.width() / img_dimensions[0];
                for (var i = crop.length - 1; i >= 0; i--) {
                    crop[i] = Math.round(crop[i] * proportion);
                };

                return crop
            };

            var record_args = function(coords){

                // Get Proportion
                proportion = img_dimensions[0] / image.width();

                // Set Crop
                var crop = [coords.x, coords.y, coords.x2, coords.y2];
                for (var i = crop.length - 1; i >= 0; i--) {
                    crop[i] = Math.round(crop[i] * proportion);
                };

                var crop = [coords.x, coords.y, coords.x + coords.w, coords.y + coords.h];

                var _scale_and_round = function(arg){
                    return Math.round(arg * proportion);
                };

                for (var i = crop.length - 1; i >= 0; i--) {
                    crop[i] = [_scale_and_round(crop[i])];
                };

                $('#id_crop').val(crop);

            };

            // It's very important that this is deferred until media is loaded
            $(window).load(function () {
                image.Jcrop({
                    {% if coordinates %}setSelect: _unconvert_crop("{{ coordinates }}"),{% endif %}
                    onChange: record_args,
                    onSelect: record_args
                });
            });


            return {}
        }();
    </script>
{% endblock content %}

cropper/templates/cropper/crop_widget.html
{% load thumbnail %}
<span class="imgWidget">
    {% if value %} 
        <b class="thumb">
            <img src="{% thumbnail value "100x100" crop=",9" %}">
        </b>
    {% endif %}
    <i class="context">
        {% if value %}            
        <span>
            <a class="thumbTxt" href="{{ link }}">{{ value|truncatechars:"25" }}</a>
        </span>
        {% endif %}
        <span>
            {% if value %} 
                Change <a class="button" href="{{ crop_url }}?post-save-redirect={{ crop_redirect }}">Crop</a>
            {% endif %}
        </span>

        <span>
            <b class="wrap_file_input">
                Select File {{ input }}
            </b>
            <i class="current"></i>
        </span>
        {% if value and not required and clear %} 
            <span>Clear {{ clear }}</span>
        {% endif %}
    </i>
</span>